// apps/react-test/src/views/antv-g6-v4/index.tsx
import { useState } from 'react';
import { exec } from '@web-test/common';
import PlayGround from '@/components/PlayGround';

const codes = import.meta.glob<string>('./codes/**/*.js', {
  eager: true,
  query: 'raw',
  import: 'default',
});

function G6Test() {
  const [codeContent, setCodeContent] = useState('');
  const [codeOptions] = useState<any[]>(() =>
    Object.keys(codes).map((key) => ({
      value: key,
      label: key,
      content: codes[key],
    }))
  );
  function handleEval(code: string) {
    exec(code);
  }
  return (
    <PlayGround value={codeContent} codeOptions={codeOptions} onChange={setCodeContent} onEval={handleEval}>
      <div id="g6v4-container" className="flex-1"></div>
    </PlayGround>
  );
}

export default G6Test;
export const meta = {
  title: 'echarts测试',
};

// apps/vue-test/src/views/antv-g6-v4.vue
<script setup lang="ts">
import { ref } from 'vue';
import { exec, getCodeOptions } from '@web-test/common';
import PlayGround from '@/components/PlayGround.vue';

const codeContent = ref('');
const codeOptions = ref<any[]>([]);

const codes = import.meta.glob<string>('#/codes/g6-v4/**/*.js', {
  eager: true,
  query: 'raw',
  import: 'default',
});
codeOptions.value = getCodeOptions(codes);

function handleEval(code: string) {
  exec(code);
}
</script>

<template>
  <PlayGround v-model="codeContent" :code-options="codeOptions" @eval="handleEval">
    <div id="g6v4-container" class="flex-1"></div>
  </PlayGround>
</template>

<script lang="ts">
export const meta = { title: 'antv/g6(4.x)测试' };
</script>
