// apps/react-test/src/components/PlayGround.tsx
import { useEffect, useRef, useState, type ComponentRef, type PropsWithChildren } from 'react';
import { Dropdown, Select, Splitter } from 'antd';
import { MoreOutlined, PlayCircleOutlined, SwapOutlined } from '@ant-design/icons';
import MonacoEditor from './MonacoEditor';
import { usePlayGroundStore } from '@/store/playGround';

type Props = PropsWithChildren<{
  value: string;
  onChange: (val: string) => void;
  // 编辑器配置选项
  editorOptions?: any;
  // 代码选项列表
  codeOptions?: any[];
  // 执行代码
  onEval?: (code: string) => void;
}>;

function PlayGround(props: Props) {
  const editorRef = useRef<ComponentRef<typeof MonacoEditor>>(null);
  const splitDirection = usePlayGroundStore((state) => state.splitDirection);
  const setSplitDirection = usePlayGroundStore((state) => state.setSplitDirection);
  const splitSize = usePlayGroundStore((state) => state.splitSize);
  const setSplitSize = usePlayGroundStore((state) => state.setSplitSize);
  function toggleDirection() {
    setSplitDirection(splitDirection === 'vertical' ? 'horizontal' : 'vertical');
  }
  function handleSplitterResize(sizes: number[]) {
    const firstSize = sizes?.[0] ?? 0;
    const totalSize = sizes?.reduce((res, num) => res + num, 0) ?? 0;
    setSplitSize((firstSize / totalSize) * 100);
  }
  const [showDefSlot, setShowDefSlot] = useState(true);
  function refreshDefSlot() {
    setShowDefSlot(false);
    setTimeout(() => {
      setShowDefSlot(true);
    });
  }
  const [codeSelect, setCodeSelect] = useState('');
  let hasInitEval = false;
  useEffect(() => {
    if (props.codeOptions?.length! > 0) {
      setCodeSelect(props.codeOptions?.[0].value);
      props.onChange?.(props.codeOptions?.[0].content);
      if (!hasInitEval) {
        hasInitEval = true;
        props.onEval?.(props.codeOptions?.[0].content);
      }
    }
  }, []);
  function handleCodeChange(value: string, option: any) {
    setCodeSelect(value);
    props.onChange?.(option.content);
  }
  function handleRun() {
    refreshDefSlot();
    props.onEval?.(props.value);
  }
  // 更多操作下拉操作
  const moreOpCallbackMap: { [key: string]: () => void } = {
    format: () => editorRef.current?.editor?.trigger('command', 'editor.action.formatDocument', {}),
  };
  // 更多操作选项
  const moreOptions = [
    {
      label: '格式化',
      key: 'format',
    },
  ];
  function handleMoreOp({ key }: { key: string }) {
    if (moreOpCallbackMap[key]) {
      moreOpCallbackMap[key]();
    }
  }
  return (
    <Splitter orientation={splitDirection} onResizeEnd={handleSplitterResize}>
      <Splitter.Panel className="flex flex-col" defaultSize={`${splitSize}%`}>
        <div className="flex flex-row justify-between items-center m-2.5 text-base">
          <div className="flex flex-row justify-end items-center gap-1">
            <Select size="small" style={{ width: 200 }} options={props.codeOptions ?? []} value={codeSelect} onChange={handleCodeChange} />
          </div>
          <div className="flex flex-row justify-end items-center gap-1">
            <SwapOutlined onClick={toggleDirection} />
            <PlayCircleOutlined onClick={handleRun} />
            <Dropdown arrow placement="bottomCenter" trigger={['click']} menu={{ items: moreOptions, onClick: handleMoreOp }}>
              <MoreOutlined />
            </Dropdown>
          </div>
        </div>
        <MonacoEditor ref={editorRef} value={props.value} editorOptions={props.editorOptions} onChange={props.onChange} />
      </Splitter.Panel>
      <Splitter.Panel className="flex flex-col" defaultSize={`${100 - splitSize}%`}>
        <div className="flex flex-col flex-1 min-w-0 min-h-0 overflow-auto">{showDefSlot ? props.children : ''}</div>
      </Splitter.Panel>
    </Splitter>
  );
}

export default PlayGround;

// src/components/PlayGround.vue
<script setup lang="ts">
import { nextTick, onMounted, ref } from 'vue';
import { NSplit, NSelect, NIcon, NDropdown } from 'naive-ui';
import { More, Sort, VideoPlay } from '@element-plus/icons-vue';
import MonacoEditor from './MonacoEditor.vue';
import { usePlayGroundStore } from '@/store/playGround';
import { storeToRefs } from 'pinia';

const props = withDefaults(
  defineProps<{
    // 编辑器配置选项
    editorOptions?: any;
    // 代码执行前的处理函数
    beforeEvalCode?: (code: string) => string;
    // 代码选项列表
    codeOptions?: any[];
  }>(),
  {
    editorOptions: () => ({}),
    codeOptions: () => [],
  }
);
const editorRef = ref<InstanceType<typeof MonacoEditor>>();
const modelValue = defineModel<string>({ default: '' });
// 代码选择
const codeSelect = ref('');
if (props.codeOptions.length > 0) {
  codeSelect.value = props.codeOptions[0].value;
  modelValue.value = props.codeOptions[0].content;
}
function handleCodeChange(_value: string, option: any) {
  modelValue.value = option.content;
}
// 分割方向
const { splitDirection, splitSize } = storeToRefs(usePlayGroundStore());
const { toggleDirection } = usePlayGroundStore();

// 刷新默认插槽（清空插槽dom，重新初始化）
const showDefSlot = ref(true);
function refreshDefSlot() {
  showDefSlot.value = false;
  nextTick(() => {
    showDefSlot.value = true;
  });
}
// 执行代码
function evalScript(codeStr: string) {
  refreshDefSlot();
  const scriptDom = document.createElement('script');
  scriptDom.type = 'module';
  if (props.beforeEvalCode) {
    scriptDom.innerHTML = props.beforeEvalCode(codeStr);
  } else {
    scriptDom.innerHTML = codeStr;
  }
  document.head.append(scriptDom);
  document.head.removeChild(scriptDom);
}
// 更多操作选项
const moreOptions = ref([
  {
    label: '格式化',
    key: 'format',
    click() {
      editorRef.value?.editor?.trigger(
        'command',
        'editor.action.formatDocument',
        {}
      );
    },
  },
]);
function handleMoreOp(_key: string, option: any) {
  if (option.click) {
    option.click();
  }
}

onMounted(() => {
  evalScript(modelValue.value);
});
</script>

<template>
  <NSplit
    class="overflow-auto"
    pane1-class="flex flex-col"
    pane2-class="flex flex-col"
    :direction="splitDirection"
    v-model:size="splitSize"
  >
    <template #1>
      <div class="flex flex-col flex-1 overflow-auto">
        <div
          class="flex flex-row justify-between items-center mb-1 mx-2.5 text-base"
        >
          <div class="flex flex-row justify-end items-center gap-1">
            <NSelect
              v-if="props.codeOptions.length > 0"
              v-model:value="codeSelect"
              size="small"
              style="width: 200px"
              :options="props.codeOptions"
              @update-value="handleCodeChange"
            />
          </div>
          <div class="flex flex-row justify-end items-center gap-1">
            <NIcon
              :component="Sort"
              @click="toggleDirection"
              class="transition-transform"
              :style="{
                transform: `rotate(${
                  splitDirection === 'vertical' ? 0 : 90
                }deg)`,
              }"
            />
            <NIcon :component="VideoPlay" @click="evalScript(modelValue)" />
            <NDropdown
              size="small"
              trigger="click"
              placement="bottom-start"
              :options="moreOptions"
              @select="handleMoreOp"
            >
              <NIcon :component="More" />
            </NDropdown>
          </div>
        </div>
        <MonacoEditor
          ref="editorRef"
          v-model="modelValue"
          :editorOptions="props.editorOptions"
        />
      </div>
    </template>
    <template #2>
      <div class="flex flex-col flex-1 min-w-0 min-h-0 overflow-auto">
        <slot name="default" v-if="showDefSlot" />
      </div>
    </template>
  </NSplit>
</template>
